image:
  repository: dievri/9mine-serverless-fs
  pullPolicy: Always
  tag: "master"

initContainerImage:
  repository: dievri/execfuse-jinja2
  tag: "master"
  pullPolicy: Always

serviceAccount:
  create: false

securityContext: 
  privileged: true
  capabilities:
    add:
      - SYS_ADMIN

service:
  type: ClusterIP
  port: 2121

fs: |
    {% include 'common.j2' %}
    wrapper_name: serverless

    fs:
      "/":
        cache:  3600
        <<: *is_dir
        readdir: 
          list:
            - funcs
            - ctl
            - k8s
        "/funcs":
          <<: *is_dir
          cache: 3600
          readdir:
            list:
              - kubeless
          "/kubeless":
            <<: *is_dir
            cache: 15
            readdir: 
              sh: kubeless function list -n default -o json | jq -r '.[].metadata.name'
            "/.*": 
              <<: *is_file
              name: func_name
              cache: 3600
              read_file: 
                sh: |
                  kubeless function call ${func_name} -n default
        "/ctl":
          <<: *is_dir
          cache: 3600
          readdir:
            list:
              - kubeless
          "/kubeless":
            <<: *is_dir
            readdir:
              list:
                - python
                - nodejs
                - golang
                - ruby
                - php
            "/python":
              <<: *is_file
              write_file: 
                sh: >
                  export TEMP_DIR=`mktemp -d /tmp/kubeless_XXXXXXX`;
                  cd $TEMP_DIR;
                  export FUNC_NAME=python-`date +%s`;
                  sls create --template kubeless-python --name $FUNC_NAME;
                  sed -i'' "s/hello/$FUNC_NAME/g" serverless.yml handler.py;
                  cat $PAYLOAD_FILE > handler.py;
                  sls plugin install --name serverless-kubeless;
                  npm install;
                  sls deploy;
            "/nodejs":
              <<: *is_file
              write_file: 
                sh: >
                  export TEMP_DIR=`mktemp -d /tmp/kubeless_XXXXXXX`;
                  cd $TEMP_DIR;
                  export FUNC_NAME=nodejs-`date +%s`;
                  sls create --template kubeless-nodejs --name $FUNC_NAME;
                  sed -i'' "s/hello/$FUNC_NAME/g" serverless.yml handler.js;
                  cat $PAYLOAD_FILE > handler.js;
                  sls plugin install --name serverless-kubeless;
                  npm install;
                  sls deploy;

        "/k8s":
          <<: *is_dir
          readdir:
            list:
              - kubeconfig
          "/kubeconfig":
            <<: *is_file
            write_file: 
              sh: |
                test -d ${HOME}/.kube || mkdir ${HOME}/.kube  
                cat $CACHE_FILE_NAME > ${HOME}/.kube/config
            read_file: 
              sh: cat ${HOME}/.kube/config
