image:
  repository: dievri/9mine-serverless-fs
  pullPolicy: Always
  tag: "master"

service:
  type: ClusterIP
  port: 3213

fs: |
    {% include 'common.j2' %}
    wrapper_name: serverless

    fs:
      "/":
        cache:  3600
        <<: *is_dir
        readdir: 
          list:
            - funcs
            - ctl
            - k8s
        "/funcs":
          <<: *is_dir
          cache: 3600
          readdir:
            list:
              - kubeless
          "/kubeless":
            <<: *is_dir
            cache: 15
            readdir: 
              sh: kubeless function list -n default -o json | jq -r '.[].metadata.name'
            "/.*": 
              <<: *is_file
              name: func_name
              cache: 3600
              read_file: 
                sh: |
                  kubeless function call ${func_name} -n default
        "/ctl":
          <<: *is_file
          cache: 3600
          readdir:
            list:
              - kubeless
            
        "/k8s":
          <<: *is_dir
          readdir:
            list:
              - kubeconfig
          "/kubeconfig":
            <<: *is_file
            write_file: 
              sh: |
                test -d ${HOME}/.kube || mkdir ${HOME}/.kube  
                cat $CACHE_FILE_NAME > ${HOME}/.kube/config
            read_file: 
              sh: cat ${HOME}/.kube/config
